DROP DATABASE IF EXISTS treble_finder_db;
CREATE DATABASE treble_finder_db;

INSERT INTO skills (id, name) VALUES (1, 'Accordion');
INSERT INTO skills (id, name) VALUES (2, 'Bagpipes');
INSERT INTO skills (id, name) VALUES (3, 'Banjo');
INSERT INTO skills (id, name) VALUES (4, 'Bass guitar');
INSERT INTO skills (id, name) VALUES (5, 'Bassoon');
INSERT INTO skills (id, name) VALUES (6, 'Berimbau');
INSERT INTO skills (id, name) VALUES (7, 'Bongo');
INSERT INTO skills (id, name) VALUES (8, 'Cello');
INSERT INTO skills (id, name) VALUES (9, 'Clarinet');
INSERT INTO skills (id, name) VALUES (10, 'Clavichord');
INSERT INTO skills (id, name) VALUES (11, 'Cor anglais');
INSERT INTO skills (id, name) VALUES (12, 'Cornet');
INSERT INTO skills (id, name) VALUES (13, 'Cymbal');
INSERT INTO skills (id, name) VALUES (14, 'Didgeridoo');
INSERT INTO skills (id, name) VALUES (15, 'Double bass');
INSERT INTO skills (id, name) VALUES (16, 'Drum kit');
INSERT INTO skills (id, name) VALUES (17, 'Euphonium');
INSERT INTO skills (id, name) VALUES (18, 'Flute');
INSERT INTO skills (id, name) VALUES (19, 'French horn');
INSERT INTO skills (id, name) VALUES (20, 'Glass harmonica');
INSERT INTO skills (id, name) VALUES (21, 'Glockenspiel');
INSERT INTO skills (id, name) VALUES (22, 'Gong');
INSERT INTO skills (id, name) VALUES (23, 'Guitar');
INSERT INTO skills (id, name) VALUES (24, 'Hang');
INSERT INTO skills (id, name) VALUES (25, 'Harmonica');
INSERT INTO skills (id, name) VALUES (26, 'Harp');
INSERT INTO skills (id, name) VALUES (27, 'Harpsichord');
INSERT INTO skills (id, name) VALUES (28, 'Hammered dulcimer');
INSERT INTO skills (id, name) VALUES (29, 'Hurdy gurdy');
INSERT INTO skills (id, name) VALUES (30, 'Jew’s harp');
INSERT INTO skills (id, name) VALUES (31, 'Kalimba');
INSERT INTO skills (id, name) VALUES (32, 'Lute');
INSERT INTO skills (id, name) VALUES (33, 'Lyre');
INSERT INTO skills (id, name) VALUES (34, 'Mandolin');
INSERT INTO skills (id, name) VALUES (35, 'Marimba');
INSERT INTO skills (id, name) VALUES (36, 'Melodica');
INSERT INTO skills (id, name) VALUES (37, 'Oboe');
INSERT INTO skills (id, name) VALUES (38, 'Ocarina');
INSERT INTO skills (id, name) VALUES (39, 'Octobass');
INSERT INTO skills (id, name) VALUES (40, 'Organ');
INSERT INTO skills (id, name) VALUES (41, 'Oud');
INSERT INTO skills (id, name) VALUES (42, 'Pan Pipes');
INSERT INTO skills (id, name) VALUES (43, 'Pennywhistle');
INSERT INTO skills (id, name) VALUES (44, 'Piano');
INSERT INTO skills (id, name) VALUES (45, 'Piccolo');
INSERT INTO skills (id, name) VALUES (46, 'Pungi');
INSERT INTO skills (id, name) VALUES (47, 'Recorder');
INSERT INTO skills (id, name) VALUES (48, 'Saxophone');
INSERT INTO skills (id, name) VALUES (49, 'Sitar');
INSERT INTO skills (id, name) VALUES (50, 'Synthesizer');
INSERT INTO skills (id, name) VALUES (51, 'Tambourine');
INSERT INTO skills (id, name) VALUES (52, 'Timpani');
INSERT INTO skills (id, name) VALUES (53, 'Triangle');
INSERT INTO skills (id, name) VALUES (54, 'Trombone');
INSERT INTO skills (id, name) VALUES (55, 'Trumpet');
INSERT INTO skills (id, name) VALUES (56, 'Theremin');
INSERT INTO skills (id, name) VALUES (57, 'Tuba');
INSERT INTO skills (id, name) VALUES (58, 'Ukulele');
INSERT INTO skills (id, name) VALUES (59, 'Viola');
INSERT INTO skills (id, name) VALUES (60, 'Violin');
INSERT INTO skills (id, name) VALUES (61, 'Whamola');
INSERT INTO skills (id, name) VALUES (62, 'Xylophone');
INSERT INTO skills (id, name) VALUES (63, 'Zither');

INSERT INTO genres(name) VALUES("Rock");
INSERT INTO genres(name) VALUES("Blues");
INSERT INTO genres(name) VALUES("Funk");
INSERT INTO genres(name) VALUES("Country");
INSERT INTO genres(name) VALUES("Folk");
INSERT INTO genres(name) VALUES("World");
INSERT INTO genres(name) VALUES("Jazz");
INSERT INTO genres(name) VALUES("Gospel");
INSERT INTO genres(name) VALUES("Bluegrass");
INSERT INTO genres(name) VALUES("Raggae");
INSERT INTO genres(name) VALUES("Pop");
INSERT INTO genres(name) VALUES("Soul");
INSERT INTO genres(name) VALUES("Latin");